### ISSUE TITLE
python ./code/gui.py error

### ISSUE THREAD

**Issue by panovr** [IvanLi123/AttnGAN-SpeakOutAndGetYourBird#1]
Running the command `python ./code/gui.py` will have some errors:

> Traceback (most recent call last):
  File "./code/gui.py", line 394, in <module>
    app = Application(master=root)
  File "./code/gui.py", line 391, in __init__
    self.create_widgets()
  File "./code/gui.py", line 16, in create_widgets
    self.image = Image.open('pictures/Backgrounds_bird.jpg')
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'pictures/Backgrounds_bird.jpg'

However, running `python ./gui.py` in `code` folder is fine.

**Comment by IvanLi123** [comment]
Sorry for the delay. When we were running this demo, we just simply cd into code file. I have changed the running command. BTW, in file gui.py, 387 line, you can lower the threshold. Since in the poster session day, the noise is huge, we set this threshold bigger than usual. It might improve the voice recognition accuracy.

**Comment by panovr** [comment]
@IvanLi123 Thanks!
